import { Inter } from 'next/font/google'
import NavBar from './components/NavBar/NavBar'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
	title: 'Film',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<NavBar />
				<div className='container'>{children}</div>
			</body>
		</html>
	)
}
